version: "3.9"
services:
  app:
    build: .
    ports:
      - '9000:9000'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:33060/demo
      MYSQL_DATABASE: 'demo'
      MYSQL_USER: 'demo'
      MYSQL_PASSWORD: 'secret2'
      MYSQL_ROOT_PASSWORD: 'secret1'
    restart: on-failure
    network_mode: bridge
    depends_on:
    - mysql

  mysql:
    image: mysql/mysql-server:5.7
    ports:
      - '33060:3306'
    environment:
      MYSQL_DATABASE: 'demo'
      MYSQL_USER: 'demo'
      MYSQL_PASSWORD: 'secret2'
      MYSQL_ROOT_PASSWORD: 'secret1'
    restart: on-failure
    network_mode: bridge


